- name: Deploy to ECS
  hosts: localhost
  connection: local
  vars:
    ecs_cluster: "flask-app"
    ecs_service: "flask-app-service-3f7o50y4"
    container_name: "my-api"
    image_repo: "732095247734.dkr.ecr.us-east-1.amazonaws.com/my-aws-app/my-api"
    image_tag: "{{ image_tag }}"

  tasks:
    # create new task revision
    - name: Edit ECS task definition to use new image
      community.aws.ecs_taskdefinition:
        family: flask-app
        containers: 
          - name: "{{ container_name }}"
            image: "{{ image_repo }}:{{ image_tag }}"
            "essential": true
            "portMappings": 
                - containerPort: 5000
                  hostPort: 5000
                  protocol: tcp
        region: eu-north-1

    - name: Update ECS service
      community.aws.ecs_service:
        name: "{{ ecs_service }}"
        cluster: "{{ ecs_cluster }}"
        task_definition: flask-app
        desired_count: 1
        force_new_deployment: true
        region: eu-north-1
