- name: Deploy to ECS
  hosts: localhost
  connection: local
  vars:
    ecs_cluster: "flask-app"
    ecs_service: "flask-app-service-3f7o50y4"
    container_name: "my-api"
    image_repo: "732095247734.dkr.ecr.us-east-1.amazonaws.com/my-aws-app/my-api"
    image_tag: "{{ image_tag }}"

  tasks:
    # create new task revision
    - name: Edit ECS task definition to use new image
      community.aws.ecs_taskdefinition:
        family: flask-app
        network_mode: awsvpc
        cpu: 256
        memory: 512
        execution_role_arn: arn:aws:iam::732095247734:role/ecsTaskExecutionRole
        task_role_arn: arn:aws:iam::732095247734:role/ecsTaskExecutionRole
        containers: 
          - name: "{{ container_name }}"
            image: "{{ image_repo }}:{{ image_tag }}"
            "essential": true
            "portMappings": 
                - containerPort: 5000
                  hostPort: 5000
                  protocol: tcp
        region: eu-north-1
        state: present
        register: task_def_out

    - name: Update ECS service
      community.aws.ecs_service:
        name: "{{ ecs_service }}"
        cluster: "{{ ecs_cluster }}"
        task_definition: "{{ task_def_out.task_definition.task_definition_arn }}"
        desired_count: 1
        launch_type: FARGATE
        network_configuration:
          awsvpc_configuration:
            subnets:
              - subnet-024bad37e2fe12ca5 
              - subnet-04a6758938e0a3ca2 
              - subnet-0e26f8a1bb629fad6
            security_groups:
              - sg-08736ffd0252f61e2
            assign_public_ip: yes
        state: present
        region: eu-north-1
