name: Deploy to EC2

on:
  push:
    branches: ['main'] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short commit hash
        id: vars
        run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Run Ansible Playbook on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/my-aws-app
            git pull
            ansible-playbook ansible/deploy-ec2.yml -e "image_tag=${{ env.GIT_COMMIT }}"
