name: Deploy Flask to ECS

on:
  push:
    branches: [deploy_ecs]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin 732095247734.dkr.ecr.eu-north-1.amazonaws.com

    - name: Build, tag and push Docker image
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        docker build -t flask-app:$IMAGE_TAG .
        docker tag flask-app:$IMAGE_TAG 732095247734.dkr.ecr.eu-north-1.amazonaws.com/my-aws-app/flask-app:$IMAGE_TAG
        docker push 732095247734.dkr.ecr.eu-north-1.amazonaws.com/my-aws-app/flask-app:$IMAGE_TAG

    - name: Run Ansible to update ECS task
      run: |
        ansible-playbook deploy-to-ecs.yml -e image_tag=$(git rev-parse --short HEAD)

